### PR TITLE
Fix layout regression bug in AdvCore with FV3+ADV

### PR DESCRIPTION
**Pull request by sdrabenh**
This is 0-diff in the stock configuration. However, these changes fix the layout regression issue when the following lines are enabled in `AGCM.rc`:

`DYCORE: FV3+ADV`
`AdvCore_Advection: 1`

### CODE REVIEW

**Comment by wmputman** [comment]
There are more updates needed. I will make a new commit today

**Review by wmputman — APPROVED** [review]

**Comment by mathomp4** [comment]
@wmputman This PR is throwing a failure in the CI testing in https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/pull/262 (which exercises it). It looks like when you build with `FV_PRECISION=R8` an interface is wrong:

```
/root/project/GEOSfvdycore/src/Components/@FVdycoreCubed_GridComp/@fvdycore/model/fv_grid_utils.F90(3184): error #6633: The type of the actual argument differs from the type of the dummy argument.   [PEM]
        p4 = g_sum(domain, pem, is, ie, js, je, ng, area, 1)
---------------------------^
```
I think the issue is that `pem` is declared as:
```
  real, allocatable:: pem(:,:)
```
and when you compile as R8, `real` is now `REAL64` and `g_sum` is now a "fixed" `REAL32` routine.

**Comment by mathomp4** [comment]
@wmputman @sdrabenh I worked with @tclune and I think we have a fix for the `FV_PRECISION=R8` case. I'm compiling now and then I'll test GEOS to make sure I didn't break anything.

But one of you might either have to test the FV3+ADV case or teach me how to run that!
